// Import the `ClerkProvider` component to handle authentication and user management
import { ClerkProvider } from "@clerk/nextjs";

// Import the `dark` theme from Clerk for consistent styling
import { dark } from "@clerk/themes";

// Import the `Metadata` type from Next.js for defining metadata for the app
import type { Metadata } from "next";

// Import Google Fonts `Geist` and `Geist_Mono` for custom typography
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS styles
import "./globals.css";

// Import the `Header` component, which is displayed at the top of every page
import Header from "../components/Header";

// Configure the `Geist` font with custom CSS variable and subset
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configure the `Geist_Mono` font with custom CSS variable and subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the application, such as the title and description
export const metadata: Metadata = {
  title: "Create Next App", // The title of the application
  description: "Generated by create next app", // A brief description of the app
};

// Define the `RootLayout` component, which wraps the entire application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // The children components to be rendered inside the layout
}>) {
  return (
    // Wrap the application with the `ClerkProvider` for authentication and theming
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Render the `Header` component at the top of the page */}
          <Header />

          {/* Render the main content of the page */}
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
